tap "afnanenayet/tap"
tap "cloudfoundry/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "screenplaydev/tap"
tap "starkandwayne/cf"
tap "uptech/oss"
brew "autoconf"
brew "automake"
brew "asdf"
brew "awscli"
brew "bash"
brew "bat"
brew "bison"
brew "bosh-cli"
brew "certbot"
brew "cheat"
brew "cmake"
brew "darksky-weather"
brew "direnv"
brew "dnsmasq"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "glab"
brew "libffi"
brew "gnu-sed"
brew "pkg-config"
brew "gnupg"
brew "go"
brew "helm"
brew "imapsync"
brew "oniguruma"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "krew"
brew "kubie"
brew "lazygit"
brew "libiconv"
brew "libvterm"
brew "qemu"
brew "lima"
brew "llvm"
brew "lua"
brew "luajit-openresty"
brew "luarocks"
brew "markdown"
brew "marp-cli"
brew "mas"
brew "minikube"
brew "tree-sitter"
brew "neovim"
brew "pinentry-mac"
brew "podman"
brew "prettier"
brew "ripgrep"
brew "rustup-init"
brew "skopeo"
brew "starship"
brew "stow"
brew "subversion"
brew "tmate"
brew "tmux"
brew "tree"
brew "vault"
brew "wget"
brew "whois"
brew "z"
brew "zlib"
brew "screenplaydev/tap/graphite"
brew "starkandwayne/cf/genesis"
brew "starkandwayne/cf/safe"
brew "starkandwayne/cf/spruce"
cask "1password"
cask "around"
cask "astropad"
cask "balenaetcher"
cask "carbon-copy-cloner"
cask "docker"
cask "elgato-stream-deck"
cask "emacs"
cask "expressvpn"
cask "firefox"
cask "font-fantasque-sans-mono"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-powerline-symbols"
cask "font-source-code-pro"
cask "goneovim"
cask "google-chrome"
cask "hammerspoon"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keybase"
cask "keyboard-maestro"
cask "ledger-live"
cask "macvim"
cask "microsoft-teams"
cask "mmhmm"
cask "moom"
cask "multipass"
cask "notion"
cask "nova"
cask "obsidian"
cask "omnifocus"
cask "raindropio"
cask "raycast"
cask "signal"
cask "skype"
cask "slack"
cask "soundsource"
cask "tower"
cask "transmit"
cask "tunnelblick"
cask "visual-studio-code"
cask "wezterm"
cask "xquartz"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "ColorSlurp", id: 1287239339
mas "com.echodot.Red", id: 1491764008
mas "Edison Mail", id: 1489591003
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "Harvest", id: 506189836
mas "Hologram Desktop", id: 1529001798
mas "iMovie", id: 408981434
mas "iNet Network Scanner", id: 403304796
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "Notion Web Clipper", id: 1559269364
mas "Numbers", id: 409203825
mas "Overlap", id: 1516950324
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "Save to Raindrop.io", id: 1549370672
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
