add_newline = false

[directory]
format = "[$path](underline #f57800)[$read_only]($read_only_style) "
truncation_length = 3
home_symbol = "~"
read_only_style = "bold red"

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[✗ ](bold red)"

[cmd_duration]
min_time = 100
format = " [took](bold yellow) [$duration](bold green)"

[aws]
format = "on [$symbol$region]($style) "
[aws.region_aliases]
us-east-1 = "us-e1"
us-east-2 = "us-e2"
eu-west-1 = "eu-w1"
eu-west-2 = "eu-w2"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[directory.substitutions]
"a/github/tetra" = "tetra"

[env_var.TS_ENV]
default = "dev"
format = "tf_env: [$env_value]($style) "
