#!/usr/bin/env bash
#
#
set -e

# keep dat sudo alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


# install nix
if [ ! -d /nix ]; then
  sudo mv /etc/zprofile /etc/zprofile.orig
  sudo mv /etc/zshrc /etc/zshrc.orig

  sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
  . ${HOME}/.nix-profile/etc/profile.d/nix.sh
  mkdir -p /nix/var/nix/profiles/per-user/root/channels

  nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
  ./result/bin/darwin-installer
  rm ./result
fi

nix-env -f '<nixpkgs>' -iA nixUnstable
nix-channel --update

# stow'em
stow -v -d ~/a/dotfiles/stowage -t $HOME starship lvim gh git ctags ruby tmux iterm2 zsh nixpkgs

echo "Done."
