#!/usr/bin/env bash
#
#
# set -e

# keep dat sudo alive
echo 'We need sudo...gimme!'
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

which brew
if [ $? -eq 0 ]; then
  echo "Homebrew already installed"
else
  echo "Installing homebrew and xcode tools"
  xcode-select --install
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

[[ -z ${SKIP_BUNDLER} ]] && brew bundle || echo "Skipping bundler"

# stow'em
stow -v -d ~/a/dotfiles/stowage -t $HOME gh git ctags ruby tmux iterm2 npm zsh

# Lunarvim
LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
rm -rf ~/.config/lvim/*
stow -v -d ~/a/dotfiles/stowage -t $HOME lvim

echo "Done."
